version: '3.3'

services:
    zen:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: zen
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}php/7.2.8-r1:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}nginx_base/1.15.1:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}php/7.2.8-r1:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: zenphoto
        container_name: zen
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
            ZEN_HOST: mysql
            ZEN_PASS: $CFG_PASS
            ZEN_USER: $CFG_USER
        hostname: zen
        image: ${DOCKER_REGISTRY:-}${OS:-}zenphoto/1.5:${CONTAINER_TAG:-latest}
#        links:
#            - mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8004:80
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log
            - ./vols/photos:/var/www/albums
