version: '3.5'

services:
    zen:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: zen
                CONTAINER_VERSION: 1.0.6
                FROM_BASE: php5:latest
            cache_from:
		- alpine:3.6
		- base_container:latest
		- supervisord:latest
		- php5:latest
            context: .
            dockerfile: Dockerfile
        container_name: zen
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            ZEN_HOST: mysql
            ZEN_PASS: ${CFG_PASS}
            ZEN_USER: ${CFG_USER}
        hostname: zen
        image: zenphoto:latest
#        links:
#            - mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8004:80
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
            - ./vols/photos:/var/www/albums
