version: '3.5'

services:
    zen:
        build:
            args:
                CONTAINER_VERSION: 1.0.0
                FROM_BASE: base_container:20180214
                DBHOST: 'mysql'
                DBPASS: ${CFG_MYSQL_PASSWORD}
                DBUSER: ${CFG_MYSQL_USER}
            context: .
        container_name: zen
        environment:
            DBHOST: mysql
            DBPASS: ${CFG_MYSQL_PASSWORD}
            DBUSER: ${CFG_MYSQL_USER}
        hostname: zen
        image: zenphoto:20180217
#        links:
#            - mysql
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        ports:
            - 8004:80
#        restart: unless-stopped
        volumes:
            - ../zen/vols/log:/var/log 
            - ../zen/vols/photos:/var/www/albums
