version: '3.5'

services:
    zen:
        build:
            context: ../zen
            args:
                TZ: "America/New_York"  
                DBUSER: ${CFG_MYSQL_USER}
                DBPASS: ${CFG_MYSQL_PASSWORD}
                DBHOST: 'mysql'
        image: zenphoto:20171222
        container_name: zen
        hostname: zen
#        restart: unless-stopped
        links:
            - mysql
        environment:
            TZ: "America/New_York"
            DBUSER: ${CFG_MYSQL_USER}
            DBPASS: ${CFG_MYSQL_PASSWORD}
            DBHOST: 'mysql'
        volumes:
            - ../zen/vols/photos:/var/www/albums
            - ../zen/vols/log:/var/log 
        ports:
            - 8004:80
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
