version: '3.3'

# repo: https://github/ballab1/zenphoto.git
# containerOS: alpine

services:
    zen:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: zen
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP7_VERSION:-7.2.8-r1}:${BASE_TAG:-latest}
                ZEN_VERSION: ${ZEN_VERSION:-1.5}
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}:${OS_VERSION:-3.8}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/nginx-base/${NGINX_VERSION:-1.15.3}:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/php/${PHP7_VERSION:-7.2.8-r1}:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: zenphoto
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: zen
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS_FILE: /run/secrets/supervisord.pwd
            SUPERVISORD_USER: $CFG_USER
            ZEN_HOST: mysql
            ZEN_PASS_FILE: /run/secrets/zenphoto.pwd
            ZEN_USER: $CFG_USER
#            PWD_PROTECTED: 'true'
#            WEB_USER_ID: $CFG_USER
#            WEB_USER_PASS_FILE: /run/secrets/web_user.pwd
        hostname: zen
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/zenphoto/${ZEN_VERSION:-1.5}:${CONTAINER_TAG:-latest}
#        links:
#            - mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8004:80
#        restart: unless-stopped
        secrets:
            - supervisord.pwd
            - zenphoto.pwd
#            - web_user.pwd
        volumes:
            - ./vols/log:/var/log
            - ./vols/photos:/var/www/albums

secrets:
   supervisord.pwd:
     file: ~/.inf/secrets/bobb.password
   zenphoto.pwd:
     file: ~/.inf/secrets/bobb.password
