version: '3.3'

services:
    zen:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: zen
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: php7:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.8
                - base_container:${CONTAINER_TAG:-latest}
                - supervisord:${CONTAINER_TAG:-latest}
                - php7:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: zen
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER 
            ZEN_HOST: mysql
            ZEN_PASS: $CFG_PASS
            ZEN_USER: $CFG_USER
        hostname: zen
        image: zenphoto:${CONTAINER_TAG:-latest}
#        links:
#            - mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8004:80
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
            - ./vols/photos:/var/www/albums
