version: '3.5'

services:
    zen:
        build:
            args:
                CONTAINER_NAME: zen
                CONTAINER_VERSION: 1.0.6
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180314
                DBHOST: mysql
                DBPASS: ${CFG_MYSQL_PASSWORD}
                DBUSER: ${CFG_MYSQL_USER}
            context: .
            dockerfile: Dockerfile
        container_name: zen
        environment:
            DBHOST: mysql
            DBPASS: ${CFG_MYSQL_PASSWORD}
            DBUSER: ${CFG_MYSQL_USER}
        hostname: zen
        image: zenphoto:20180314
#        links:
#            - mysql
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8004:80
#        restart: unless-stopped
        volumes:
            - ./vols/log:/var/log 
            - ./vols/photos:/var/www/albums
