version: '3.1'

services:
    zen:
        build:
            context: ../zenphoto
            args:
                TZ: "America/New_York"
        image: zenphoto:20171210
        container_name: zen
        hostname: zen
#        restart: unless-stopped
        links:
            - mysql
        environment:
            TZ: "America/New_York"
            DBUSER: ${CFG_MYSQL_USER}
            DBPASS: ${CFG_MYSQL_PASSWORD}
            DBHOST: 'mysql'
        volumes:
            - ../zenphoto/photos:/var/www/zen/albums
            - ../zenphoto/log:/var/log 
        ports:
            - 8004:80
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
